import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import MaterialTable from 'material-table'

class App extends Component {
  render() {
    return (
      <div style={{ maxWidth: '100%' }}>
        <MaterialTable
          options={{
            tableLayout: "auto",
            maxBodyHeight: 700,
            pageSize: 5,
            pageSizeOptions: [5,10,20,50,100],
            style: {class: "table table-striped scroll"},
            headerStyle: {fontWeight: "bold"},
            // headerStyle: {backgroundColor: "#327d83", color: "white"},
            rowStyle: {fontSize: "medium"},
            showTitle: true,
            exportButton: true,
            exportAllData: true,
          }}
          columns={[
            { title: 'Organism', field: 'organism', defaultSort: 'asc', width: "10%"},
            { title: 'Biosample', field: 'biosample', width: "10%"},
            { title: 'Assay', field: 'assay', width: "20%"}, 
            { title: 'Enzyme', field: 'enzyme', width: "10%"}, 
            { title: 'Archive', field: 'archive', width: "10%"}, 
            { title: 'Library', field: 'library', width: "10%"}, 
            { title: 'PMID', field: 'pmid', render: rowData => <a href={'https://pubmed.ncbi.nlm.nih.gov/'+rowData.pmid}>{rowData.pmid}</a> , width: "10%"},
            { title: 'Genes targeted', field: 'genes', width: "20%"},
            // { title: 'sgRNA Library', field: 'sgrna_library'},
          ]}
          data={[
            {organism: 'Mus musculus', biosample: 'Embryonic Stem Cell', assay: 'Knockout by NHEJ – proliferation, Knockout by NHEJ – single genomic target', genes: '1700016K19Rik, B4galt7, Cstf3, Defa41, Dpm1, Dpm2, Dpm3, Ext2, Gpaa1, Letmd1, Lypla1, Mlh1, Msh2, Msh6, Pgap2, Piga, Pigb, Pigc, Pigf, Pigg, Pigh, Pigk, Pigl, Pigm, Pign, Pigo, Pigp, Pigq, Pigs, Pigt, Pigu, Pigv, Pigw, Pigx, Pms2, Prkg1, Pyurf, Trpc2', enzyme: 'SpCas9', archive: 'European Nucleotide Archive', library: 'GeCKO v2', pmid: '24535568'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'cav1, cav3, cdh2, cdh23, chrd, coch, col11a2, crym, ctnnb1, cx30.3, cx35.4, espn, espnlb, eya4, fgf24, fndc7rs1, fut8a, gpsm2, grhl2a, grhl2b, GSDME, gsdmeb, hgfa, hgfb, hif1ab, hspa5, hspe1, hyou1, igf2bp2b, igfbp7, ildr1a, ildr1b, junba, junbb, kars1, krt15, lhfpl5a, loxhd1a, loxhd1b, man1a1, man1b1a, man2a1, man2b1, marveld2a, marveld2b, mgat1b, mgat2, mgat3a, mgat4a, mgat4b, mgat4c, mgat5, msrb3, myh9a, myh9b, myo15aa, myo15ab, myo3a, myo6a, myo7aa, oga, ogt.1, pcdh15b, pou4f3, prdx2, prdx3, prdx4, prps1a, prps1b, ptprn2, ptprna, ptprnb, ptprq, sesn1, sh3pxd2aa, si:ch211-214j24.10-201, slc26a4, slc26a5, smpx, tecta, tjp2a, tjp2b, TMC1, tmie, tmprss3a, tyr, ush1c, wfs1b, zgc:77486', enzyme: 'Cas9', archive: 'NCBI BioProject', library: '', pmid: '26048245'},
            {organism: 'Drosophila melanogaster', biosample: 'S2R+', assay: 'Knockout by NHEJ – proliferation', genes: '', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '26165496'},
            {organism: 'Mus musculus', biosample: 'bone marrow-derived macrophage', assay: 'Knockout by NHEJ – single genomic target', genes: 'Casp1, Gsdmd', enzyme: 'Cas9', archive: '', library: '', pmid: '27329339'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Dual sgRNA-directed deletion', genes: 'CDKN2B-AS1', enzyme: 'Cas9', archive: '', library: '', pmid: '27539542'},
            {organism: 'Zea mays', biosample: 'plant embryo, Protoplast', assay: 'Knockout by NHEJ – single genomic target', genes: 'matrilineal1', enzyme: 'Cas9', archive: '', library: '', pmid: '28179149'},
            {organism: 'Strongylocentrotus purpuratus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'SP-NAN2', enzyme: 'Cas9-FLAG-NLS', archive: '', library: '', pmid: '28235822'},
            {organism: 'Chlorocebus sabaeus, Homo sapiens', biosample: 'HEK293, HepG2, Vero cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'IFNAR1, IFNAR2, UQCC3', enzyme: 'Cas9', archive: '', library: '', pmid: '28418037'},
            {organism: 'Mus musculus', biosample: 'Neural Stem Cell, NIH-3T3 cell, obsolete_C57BL/6, primary cell line, Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'Bcan, Egfr, Fgfr3, Gga2, Ntrk1, Prkcb, Sec61g, Tacc3', enzyme: 'SpCas9', archive: '', library: '', pmid: '28695888'},
            {organism: 'Macaca fascicularis', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion', genes: 'SHANK3', enzyme: 'SpCas9', archive: '', library: '', pmid: '28741620'},
            {organism: 'Homo sapiens', biosample: '451Lu cell, A101D, A375, HCC827, Mel888 cell', assay: 'Knockout by NHEJ – proliferation, Knockout by NHEJ – single genomic target', genes: 'FOSL1, JUN, JUNB, MAP2K1, MAP2K2, MAPK1, MAPK3', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '28976960'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'BAZ1A, BAZ1B', enzyme: 'SpCas9', archive: 'Gene Expression Omnibus', library: '', pmid: '29021563'},
            {organism: 'Daphnia magna str. Xinb3', biosample: 'germ cell', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'APZ42_020993', enzyme: 'SpCas9', archive: '', library: '', pmid: '29045453'},
            {organism: 'Homo sapiens', biosample: 'HCT116, U2OS', assay: 'Knockout by NHEJ – single genomic target', genes: 'SHMT2, SIRT5', enzyme: 'Cas9', archive: '', library: '', pmid: '29180469'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'brat, zld', enzyme: 'Cas9', archive: '', library: '', pmid: '29191977'},
            {organism: 'Mus musculus', biosample: 'Neuro-2a cell', assay: 'Dual sgRNA-directed deletion', genes: 'Cfl1', enzyme: 'pSpCas9', archive: '', library: '', pmid: '29440227'},
            {organism: 'Homo sapiens', biosample: 'HEK-293FT cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'GBA', enzyme: 'pSpCas9', archive: '', library: '', pmid: '29579237'},
            {organism: 'Arabidopsis thaliana', biosample: 'Col-0, Flower', assay: 'Knockout by NHEJ – single genomic target', genes: 'CLE25', enzyme: 'Cas9', archive: '', library: '', pmid: '29618812'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'CERS2', enzyme: 'pSpCas9', archive: '', library: '', pmid: '29632068'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'KIF18B', enzyme: 'SpCas9', archive: '', library: '', pmid: '29661912'},
            {organism: 'Homo sapiens', biosample: 'HuH-7, SMMC-7721 cell, SNU-449 cell', assay: 'Knockout by NHEJ – single genomic target, Transcriptional activation', genes: 'LINC01138', enzyme: 'Cas9, dCas9-VP64', archive: '', library: '', pmid: '29679004'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'IMPDH2', enzyme: 'Cas9', archive: '', library: '', pmid: '29706504'},
            {organism: 'Mus musculus', biosample: 'NOD mouse, zygote', assay: 'Dual sgRNA-directed deletion', genes: 'Zbtb32', enzyme: 'Cas9n', archive: '', library: '', pmid: '29707204'},
            {organism: 'Homo sapiens', biosample: 'MCF 10A, MDAMB231, NCI-N87, SKBR3', assay: 'Knockout by NHEJ – single genomic target', genes: 'PIP5K1A', enzyme: 'Cas9', archive: '', library: '', pmid: '29851245'},
            {organism: 'Gallus gallus', biosample: 'Primordial Germ Cell', assay: 'Insertion by HDR/MMEJ', genes: 'OVA', enzyme: 'hCas9', archive: '', library: '', pmid: '29976933'},
            {organism: 'Mus musculus', biosample: 'mouse embryonic stem cell', assay: 'Knockout by NHEJ – differentiation, Knockout by NHEJ – proliferation, Knockout by NHEJ – single genomic target', genes: 'Apc, Depdc5, Hgs, Kcmf1, Nelfb, Nelfcd, Nprl2, Pggt1b, Pou5f1, Ptpn23, Rictor, Stat3, Tcf7l1, Tsc1, Tsc2, Vps25, Vps39, Zfp219, Znrf3', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '29996108'},
            {organism: 'Homo sapiens', biosample: 'Jurkat, K562', assay: 'Transcriptional inhibition', genes: 'CACTIN, CDC40, DMAC1, FDFT1, FDPS, GGPS1, HMGCR, HMGCS1, HUS1, IDI1, MVD, MVK, NDUFA8, NDUFB4, PGK1, PMVK, POLD1, POLD3, PPIE, PRPF18, SNRPB, SNRPC, SQLE, SREBF2, ZNF830', enzyme: 'dCas9-KRAB', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '30033366'},
            {organism: 'Danio rerio', biosample: 'ZF4', assay: 'Knockout by NHEJ – single genomic target', genes: 'caspb', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30076291'},
            {organism: 'Clostridium beijerinckii', biosample: 'Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'LF65_01289, LF65_01851', enzyme: 'AsCpf1', archive: '', library: '', pmid: '30081040'},
            {organism: 'Homo sapiens', biosample: 'MCF 10A, MCF-7', assay: 'Knockout by NHEJ – Fluorescence, Knockout by NHEJ – single genomic target', genes: 'TRPS1', enzyme: 'Cas9, Cas9n', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '30082728'},
            {organism: 'Homo sapiens', biosample: 'SH-SY5Y', assay: 'Knockout by NHEJ – single genomic target', genes: 'STIM1', enzyme: 'Cas9n (D10A)', archive: '', library: '', pmid: '30088035'},
            {organism: 'Arabidopsis thaliana', biosample: 'Col-0, Flower', assay: 'Knockout by NHEJ – single genomic target', genes: 'ATGLCAK', enzyme: 'Cas9', archive: '', library: '', pmid: '30102814'},
            {organism: 'Homo sapiens', biosample: 'OE19, OE33', assay: 'Knockout by NHEJ – single genomic target', genes: 'SOX9', enzyme: 'SpCas9', archive: '', library: '', pmid: '30102978'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'FMRFaR', enzyme: 'Cas9', archive: '', library: '', pmid: '30110323'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'npc1', enzyme: 'Cas9', archive: '', library: '', pmid: '30135069'},
            {organism: 'Homo sapiens', biosample: 'HepaRG', assay: 'Knockout by NHEJ – single genomic target', genes: 'AHR', enzyme: 'Cas9', archive: '', library: '', pmid: '30147834'},
            {organism: 'Plasmodium falciparum NF54', biosample: 'Whole Organism', assay: 'Insertion by HDR', genes: 'PF3D7_1116800', enzyme: 'Cas9', archive: '', library: '', pmid: '30150771'},
            {organism: 'Canis lupus familiaris', biosample: 'Whole Organism', assay: 'Knockin by NHEJ – single genomic target', genes: 'DMD', enzyme: 'Cas9', archive: '', library: '', pmid: '30166439'},
            {organism: 'Mus musculus', biosample: 'Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'Abcb11, Asl, Gclc, Gss, Hpd, Por, Ugdh, Ugt1a1', enzyme: 'SpCas9', archive: '', library: '', pmid: '30170115'},
            {organism: 'Escherichia coli str. K-12 substr. MG1655', biosample: 'Whole Organism', assay: 'Transcriptional inhibition', genes: 'wcaF', enzyme: 'dCas9', archive: '', library: '', pmid: '30177768'},
            {organism: 'Rattus norvegicus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Nf1', enzyme: 'Cas9', archive: '', library: '', pmid: '30182054'},
            {organism: 'Mus musculus', biosample: 'C57BL/6N Mouse, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Trem2', enzyme: 'Cas9', archive: '', library: '', pmid: '30185230'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Rsph6a', enzyme: 'hCas9', archive: '', library: '', pmid: '30185526'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, Embryonic Stem Cell, zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Arl6ip5, C6, Ces3b, Cpn1, Itgb6, Plcb4, Sntg1', enzyme: 'hCas9', archive: '', library: '', pmid: '30188893'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'DROSHA', enzyme: 'SpCas9', archive: '', library: '', pmid: '30195795'},
            {organism: 'Homo sapiens', biosample: 'DU 145', assay: 'Knockout by NHEJ – single genomic target', genes: 'ITGA2', enzyme: 'Cas9', archive: '', library: '', pmid: '30197754'},
            {organism: 'Saccharomyces cerevisiae', biosample: 'BY4741, SK-MEL-28', assay: 'Dual sgRNA-directed deletion', genes: 'REX4, TRM10', enzyme: 'FnCpf1', archive: '', library: '', pmid: '30198089'},
            {organism: 'Capra hircus', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion', genes: 'MSTN', enzyme: 'Cas9', archive: '', library: '', pmid: '30201688'},
            {organism: 'Homo sapiens', biosample: 'Caco-2, COLO320DM, GP5d', assay: 'Knockout by NHEJ – proliferation, Transcriptional activation', genes: '', enzyme: 'Cas9, dCas9-VP64', archive: 'European Nucleotide Archive', library: 'GeCKO v2', pmid: '30202008'},
            {organism: 'Homo sapiens', biosample: 'THP-1', assay: 'Knockout by NHEJ – single genomic target', genes: 'USP47, USP7', enzyme: 'Cas9', archive: '', library: '', pmid: '30206189'},
            {organism: 'Homo sapiens', biosample: 'H9', assay: 'Knockout by NHEJ – single genomic target', genes: 'WRN', enzyme: 'Cas9', archive: '', library: '', pmid: '30206203'},
            {organism: 'Mus musculus', biosample: 'RAW264.7', assay: 'Insertion by HDR/MMEJ', genes: 'Lrp1', enzyme: 'Cas9', archive: '', library: '', pmid: '30208326'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cmtm1, Cmtm2a, Cmtm2b', enzyme: 'Cas9', archive: '', library: '', pmid: '30209135'},
            {organism: 'Danio rerio', biosample: 'AB Zebrafish, embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'rho', enzyme: 'Cas9', archive: '', library: '', pmid: '30210230'},
            {organism: 'Mus musculus', biosample: 'embryonic fibroblast', assay: 'Knockout by NHEJ – single genomic target', genes: 'Myrf', enzyme: 'Cas9', archive: '', library: '', pmid: '30213958'},
            {organism: 'Mus musculus', biosample: 'oocyte', assay: 'Dual sgRNA-directed deletion', genes: 'Tcf12', enzyme: 'Cas9', archive: '', library: '', pmid: '30217225'},
            {organism: 'Mus musculus', biosample: 'HEPA 1-6 cell, obsolete_C57BL/6, Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'Gt(ROSA)26Sor, Hpd, Pcsk9', enzyme: 'Neisseria meningitidis Cas9 ', archive: 'NCBI Sequence Read Archive', library: '', pmid: '30231914'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion, Insertion by HDR/MMEJ', genes: 'Kdm2', enzyme: 'Humanised Cas9', archive: '', library: '', pmid: '30233643'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'MSTN', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30241032'},
            {organism: 'Zea mays', biosample: 'plant embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'male sterile8', enzyme: 'Zea mays optimised SpCas9-NLS', archive: '', library: '', pmid: '30245698'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Knockout by NHEJ – single genomic target', genes: 'OAT', enzyme: 'Cas9', archive: '', library: '', pmid: '30251682'},
            {organism: 'Homo sapiens', biosample: 'HaCaT, NHEK', assay: 'Knockout by NHEJ – single genomic target', genes: 'LRRC8A', enzyme: 'SpCas9-NLS-T2A-Orange fluorescent protein', archive: '', library: '', pmid: '30252954'},
            {organism: 'Caenorhabditis elegans', biosample: 'N2, Whole Organism', assay: 'Insertion by HDR/MMEJ', genes: 'dpy-10, rap-1', enzyme: 'Cas9', archive: '', library: '', pmid: '30257933'},
            {organism: 'Homo sapiens', biosample: 'AGS', assay: 'Knockout by NHEJ – single genomic target', genes: 'LMX1A', enzyme: 'Cas9', archive: '', library: '', pmid: '30262143'},
            {organism: 'Homo sapiens', biosample: 'LNCAP', assay: 'Knockout by NHEJ – single genomic target', genes: 'UGT2B15, UGT2B17', enzyme: 'Cas9', archive: '', library: '', pmid: '30262668'},
            {organism: 'Homo sapiens', biosample: 'U-87 MG', assay: 'Knockout by NHEJ – single genomic target', genes: 'ZIC1', enzyme: 'Cas9', archive: '', library: '', pmid: '30264483'},
            {organism: 'Rattus norvegicus', biosample: 'Sprague Dawley, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Fus', enzyme: 'Cas9', archive: '', library: '', pmid: '30273830'},
            {organism: 'Mus musculus', biosample: 'obsolete_C57BL/6, zygote', assay: 'Base editing (DNA)', genes: 'Atoh1, Otof, Slc17a8, Slc26a5, Tyr', enzyme: 'Base editor 3 (BE3)', archive: '', library: '', pmid: '30275281'},
            {organism: 'Homo sapiens', biosample: 'foreskin fibroblast, primary cell line', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'PDGFRA, PDGFRB', enzyme: 'Cas9', archive: 'Journal website', library: 'GeCKO v2', pmid: '30275317'},
            {organism: 'Homo sapiens', biosample: 'HepG2', assay: 'Knockout by NHEJ – single genomic target', genes: 'HSPB1', enzyme: 'Cas9', archive: '', library: '', pmid: '30279146'},
            {organism: 'Homo sapiens', biosample: 'HCT116', assay: 'Knockout by NHEJ – single genomic target', genes: 'HERC2', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30279242'},
            {organism: 'Danio rerio', biosample: 'embryo, Tupfel Long Fin Zebrafish', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'ush2a', enzyme: 'Cas9, Cas9n', archive: '', library: '', pmid: '30281416'},
            {organism: 'Homo sapiens', biosample: 'Natural Killer Cell, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'IFIH1', enzyme: 'Cas9', archive: '', library: '', pmid: '30286211'},
            {organism: 'Mus musculus', biosample: 'bone marrow-derived macrophage, obsolete_C57BL/6, RAW264.7, Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'Green fluorescent protein, Nlrp3', enzyme: 'Cas9', archive: '', library: '', pmid: '30291237'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion, Knockout by NHEJ – single genomic target', genes: 'cnga2a, cnga2b, oxt', enzyme: 'Cas9', archive: '', library: '', pmid: '30294598'},
            {organism: 'Mus musculus', biosample: 'C57BL/6NJ, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Bcl2l11', enzyme: 'SpCas9', archive: '', library: '', pmid: '30301924'},
            {organism: 'Sus scrofa', biosample: 'fibroblast, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'APOE', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30305304'},
            {organism: 'Mus musculus', biosample: 'Embryonic Stem Cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'Dcx', enzyme: 'Cas9', archive: '', library: '', pmid: '30305734'},
            {organism: 'Homo sapiens', biosample: 'HepG2', assay: 'Knockout by NHEJ – single genomic target', genes: 'CH25H, NR1H2, NR1H3, SULT2B1', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30309895'},
            {organism: 'Homo sapiens', biosample: 'HepG2', assay: 'Knockout by NHEJ – single genomic target', genes: 'MPV17L', enzyme: 'Cas9', archive: '', library: '', pmid: '30310528'},
            {organism: 'Phaeodactylum tricornutum CCAP 1055/1', biosample: 'Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'Phatr3_J46193', enzyme: 'Cas9', archive: 'NCBI BioProject', library: '', pmid: '30310734'},
            {organism: 'Mus musculus', biosample: 'BV-2 cell', assay: 'Insertion by HDR/MMEJ', genes: 'Acox1', enzyme: 'Cas9', archive: '', library: '', pmid: '30312667'},
            {organism: 'Homo sapiens', biosample: 'SH-SY5Y', assay: 'Knockout by NHEJ – single genomic target', genes: 'NINJ2', enzyme: 'Cas9', archive: '', library: '', pmid: '30318119'},
            {organism: 'Homo sapiens', biosample: 'hTERT-RPE1 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'WDR34, WDR60', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30320547'},
            {organism: 'Xenopus tropicalis', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'neurod2', enzyme: 'Cas9', archive: '', library: '', pmid: '30323019'},
            {organism: 'Arabidopsis thaliana', biosample: 'Col-0, Flower', assay: 'Knockout by NHEJ – single genomic target', genes: 'AT2G20400', enzyme: 'Cas9', archive: '', library: '', pmid: '30327661'},
            {organism: 'Homo sapiens', biosample: 'HCT116, HT-29', assay: 'Knockout by NHEJ – single genomic target', genes: 'TM9SF2', enzyme: 'Cas9', archive: '', library: '', pmid: '30333512'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'ACTB, TP53', enzyme: 'Cas9', archive: '', library: '', pmid: '30335949'},
            {organism: 'Homo sapiens', biosample: 'H9, HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'ZEB1', enzyme: 'iCas9', archive: '', library: '', pmid: '30337365'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Ikbkb', enzyme: 'SpCas9', archive: '', library: '', pmid: '30337470'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'smarce1', enzyme: 'Cas9', archive: '', library: '', pmid: '30337622'},
            {organism: 'Homo sapiens', biosample: 'HEK293T, HeLa', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'CCR5', enzyme: 'Cas9', archive: '', library: '', pmid: '30340581'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'abcc9, kcnj8, pln', enzyme: 'nCas9', archive: '', library: '', pmid: '30355756'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Nhej1', enzyme: 'Cas9', archive: '', library: '', pmid: '30356064'},
            {organism: 'Caenorhabditis elegans', biosample: 'N2, Whole Organism', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'daf-18', enzyme: 'Cas9', archive: '', library: '', pmid: '30361258'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'bcl9, bcl9l, pygo1, pygo2', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: '', pmid: '30366904'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Dicer1', enzyme: 'SpCas9', archive: '', library: '', pmid: '30368519'},
            {organism: 'Sus scrofa', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'PDX1', enzyme: 'Cas9', archive: '', library: '', pmid: '30368976'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Mafb', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30369533'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion', genes: 'Hdac9', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30372441'},
            {organism: 'Mus musculus, Rattus norvegicus', biosample: 'C57BL/6N Mouse, Neuro-2a cell, PC12, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Chdh, Ehd1', enzyme: 'Cas9, Cas9n', archive: '', library: '', pmid: '30375401'},
            {organism: 'Homo sapiens', biosample: 'MCF 10A, MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'ARNTL, CRY1, CRY2', enzyme: 'Cas9', archive: '', library: '', pmid: '30375470'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Mab21l2', enzyme: 'Cas9n (D10A)', archive: '', library: '', pmid: '30375740'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'Megf6', enzyme: 'Cas9', archive: '', library: '', pmid: '30381865'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'hb', enzyme: 'Cas9', archive: '', library: '', pmid: '30383747'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'gldc', enzyme: 'Cas9', archive: '', library: '', pmid: '30385710'},
            {organism: 'Homo sapiens', biosample: 'A549', assay: 'Knockout by NHEJ – single genomic target', genes: 'HIF1A', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30391674'},
            {organism: 'Homo sapiens', biosample: '293T, EBC-1, Patient Derived Xenograft, SKMES1, squamous cell lung carcinoma', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target, Transcriptional activation', genes: 'CLDN1, CSMD3, FGFR2, GRM1, GRM8, PIK3CA, PIK3CG, RIT1, ZFHX4', enzyme: 'dCas9-VP64, pSpCas9, SaCas9', archive: '', library: '', pmid: '30391781'},
            {organism: 'Homo sapiens', biosample: 'MDAMB231, MDAMB468', assay: 'Knockout by NHEJ – single genomic target', genes: 'AURKB, KRAS, MELK, MYC, PLK1', enzyme: 'Cas9', archive: '', library: '', pmid: '30391850'},
            {organism: 'Mus musculus', biosample: 'B16-F1 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cyfip1, Cyfip2, Rac1, Rac2, Rac3', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30393033'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'EWSR1, FUS, MATR3, TAF15', enzyme: 'hCas9', archive: '', library: '', pmid: '30398641'},
            {organism: 'Mus musculus', biosample: 'NIH-3T3 cell, zygote', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'Phf6', enzyme: 'Cas9', archive: '', library: '', pmid: '30403997'},
            {organism: 'Homo sapiens', biosample: 'HEK293T, HepG2', assay: 'Insertion by HDR/MMEJ', genes: 'CBS', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30408270'},
            {organism: 'Homo sapiens', biosample: 'RKO, SW620', assay: 'Knockout by NHEJ – single genomic target', genes: 'PLEKHA8', enzyme: 'Cas9', archive: '', library: '', pmid: '30408464'},
            {organism: 'Danio rerio', biosample: 'AB Zebrafish, embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'kif15', enzyme: 'Cas9', archive: '', library: '', pmid: '30411440'},
            {organism: 'Homo sapiens', biosample: 'H9', assay: 'Knockin by NHEJ – single genomic target', genes: 'TRPC1', enzyme: 'Cas9', archive: '', library: '', pmid: '30423318'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'CTNNB1, LEF1, TCF7, TCF7L1, TCF7L2', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30425074'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'dguok', enzyme: 'Cas9', archive: '', library: '', pmid: '30428046'},
            {organism: 'Homo sapiens', biosample: 'NCI-H446', assay: 'Knockout by NHEJ – single genomic target', genes: 'FLI1', enzyme: 'Cas9', archive: '', library: '', pmid: '30429198'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'PGRMC1, TMEM97', enzyme: 'Cas9', archive: '', library: '', pmid: '30443021'},
            {organism: 'Homo sapiens', biosample: 'SH-SY5Y', assay: 'Knockout by NHEJ – single genomic target', genes: 'QPRT', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30443311'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, zygote', assay: 'Dual sgRNA-directed deletion', genes: 'Frmpd1', enzyme: 'SpCas9', archive: '', library: '', pmid: '30445545'},
            {organism: 'Ovis aries', biosample: 'embryo, fibroblast, primary cell line, Rambouillet', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'ALPL', enzyme: 'Cas9', archive: '', library: '', pmid: '30446691'},
            {organism: 'Mus musculus', biosample: 'CT26.WT cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cd274', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30464460'},
            {organism: 'Homo sapiens', biosample: 'HT-29', assay: 'Knockout by NHEJ – single genomic target', genes: 'SLC9A8', enzyme: 'Cas9', archive: '', library: '', pmid: '30465020'},
            {organism: 'Homo sapiens', biosample: 'Capan1', assay: 'Knockout by NHEJ – single genomic target', genes: 'GALNT3', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30466404'},
            {organism: 'Homo sapiens', biosample: 'HEK293T, MDAMB231', assay: 'Dual sgRNA-directed deletion', genes: 'ETS1', enzyme: 'Cas9', archive: '', library: '', pmid: '30467308'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Insertion by HDR/MMEJ', genes: 'ADORA2B', enzyme: 'Cas9', archive: '', library: '', pmid: '30471466'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'tyn', enzyme: 'Cas9', archive: '', library: '', pmid: '30576352'},
            {organism: 'Homo sapiens', biosample: 'OVCAR3, SKOV3', assay: 'Knockout by NHEJ – single genomic target', genes: 'MTF1', enzyme: 'Cas9n', archive: '', library: '', pmid: '30588241'},
            {organism: 'Mus musculus', biosample: 'C57BL/6N Mouse, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Kcnh6', enzyme: 'Cas9', archive: '', library: '', pmid: '30590050'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Dual sgRNA-directed deletion', genes: 'ZEB2', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30590588'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'ptprja', enzyme: 'Cas9', archive: '', library: '', pmid: '30591527'},
            {organism: 'Homo sapiens', biosample: '293T, A549, U2OS', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'TDP2', enzyme: 'Cas9', archive: '', library: '', pmid: '30593505'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'nfe2l2a', enzyme: 'Cas9', archive: '', library: '', pmid: '30594530'},
            {organism: 'Mus musculus', biosample: 'RAW264.7', assay: 'Knockout by NHEJ – single genomic target', genes: 'Gpr137b', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30595385'},
            {organism: 'Mus musculus', biosample: 'Embryonic Stem Cell', assay: 'Knockout by NHEJ – differentiation, Knockout by NHEJ – single genomic target', genes: 'Apc, Depdc5, Eed, Erlin1, Flcn, Grb2, Lamtor1, Lamtor2, Lamtor4, Lamtor5, Ptbp3, Ptpn11, Rragc, Socs3, Tcf7l1, Tfe3, Tmem127, Trp53, Tsc1, Tsc2, Wdr24', enzyme: 'Cas9, hCas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '30595499'},
            {organism: 'Homo sapiens', biosample: '293T/17 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'PDCD6IP', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30599162'},
            {organism: 'Mus musculus', biosample: 'C2C12', assay: 'Knockout by NHEJ – single genomic target', genes: 'Atf6', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30602124'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'CD46', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30603655'},
            {organism: 'Homo sapiens', biosample: '786-0, A549, MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'CD274', enzyme: 'Cas9', archive: '', library: '', pmid: '30603685'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'ncapg2', enzyme: 'Cas9', archive: '', library: '', pmid: '30609410'},
            {organism: 'Homo sapiens', biosample: 'H9', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'ADAM17', enzyme: 'eSpCas9, SpCas9', archive: '', library: '', pmid: '30610007'},
            {organism: 'Solanum lycopersicum', biosample: 'cotyledon', assay: 'Knockout by NHEJ – single genomic target', genes: 'Solyc01g096050.3, Solyc05g050560.1 ', enzyme: 'Cas9', archive: '', library: '', pmid: '30610166'},
            {organism: 'Homo sapiens', biosample: 'H9, HEK293T', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'PTCH1', enzyme: 'Cas9', archive: '', library: '', pmid: '30610186'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cmah', enzyme: 'Cas9', archive: '', library: '', pmid: '30616506'},
            {organism: 'Danio rerio', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'ints1', enzyme: 'Cas9', archive: '', library: '', pmid: '30622326'},
            {organism: 'Homo sapiens', biosample: 'MCF-7, MDAMB231', assay: 'Dual sgRNA-directed deletion', genes: 'SOX9', enzyme: 'Cas9n', archive: '', library: '', pmid: '30622340'},
            {organism: 'Sus scrofa', biosample: 'fetal cell line, primary cultured fibroblast cell, RCB0534 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'SIX1, SIX4', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30623494'},
            {organism: 'Homo sapiens', biosample: 'A549, HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'KCNN4, LAMP1', enzyme: 'Cas9', archive: '', library: '', pmid: '30626681'},
            {organism: 'Mus musculus', biosample: 'C57BL/6NJ, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Zbtb16', enzyme: 'Cas9', archive: '', library: '', pmid: '30628160'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Dual sgRNA-directed deletion', genes: 'Caap1', enzyme: 'Cas9', archive: '', library: '', pmid: '30629682'},
            {organism: 'Homo sapiens', biosample: 'A375', assay: 'Knockout by NHEJ – single genomic target', genes: 'HMOX1', enzyme: 'Cas9', archive: '', library: '', pmid: '30634993'},
            {organism: 'Homo sapiens', biosample: 'HCT116', assay: 'Insertion by HDR/MMEJ', genes: 'CDC25A, CHEK1', enzyme: 'SaCas9', archive: '', library: '', pmid: '30635443'},
            {organism: 'Homo sapiens', biosample: 'HCT116, SW480', assay: 'Knockout by NHEJ – single genomic target', genes: 'C1GALT1C1', enzyme: 'Cas9', archive: '', library: '', pmid: '30637914'},
            {organism: 'Danio rerio', biosample: 'AB Zebrafish, embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'hdac4', enzyme: 'nCas9n', archive: '', library: '', pmid: '30643696'},
            {organism: 'Solanum lycopersicum', biosample: 'cotyledon', assay: 'Knockout by NHEJ – single genomic target', genes: 'Solyc11g030600.3', enzyme: 'Cas9', archive: '', library: '', pmid: '30652405'},
            {organism: 'Homo sapiens', biosample: 'Capan1', assay: 'Knockout by NHEJ – single genomic target', genes: 'HMOX1', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30653942'},
            {organism: 'Homo sapiens', biosample: 'SK-MEL-28, SUM159PT', assay: 'Transcriptional activation', genes: 'PTEN, SERPINB5', enzyme: 'hSp dCas9-VPR', archive: '', library: '', pmid: '30654190'},
            {organism: 'Homo sapiens', biosample: 'HAP-1, Huh-7.5.1 cell', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'GNPTAB, NPC1', enzyme: 'Cas9', archive: 'Journal website', library: 'GeCKO v2', pmid: '30655525'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'NHEJ and HDR/MMEJ', genes: 'NCSTN', enzyme: 'hCas9', archive: '', library: '', pmid: '30656721'},
            {organism: 'Homo sapiens', biosample: 'HAP-1, HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'UBE2G2, UBE2J1, UBE2J2', enzyme: 'Cas9', archive: '', library: '', pmid: '30658189'},
            {organism: 'Homo sapiens', biosample: 'glioblastoma multiforme, LN-229, primary cell line, U-87 MG', assay: 'Knockout by NHEJ – single genomic target', genes: 'LAMA4, LAMB1', enzyme: 'Cas9', archive: '', library: '', pmid: '30659021'},
            {organism: 'Homo sapiens', biosample: 'HeLa, MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'ITGA3', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30659093'},
            {organism: 'Gallus gallus', biosample: 'CEF cell, UMNSAH/DF-1 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'TBK1', enzyme: 'Cas9', archive: '', library: '', pmid: '30662438'},
            {organism: 'Solanum lycopersicum, Solanum tuberosum', biosample: 'cotyledon, stem', assay: 'Base editing (DNA)', genes: 'PGSC0003DMG400034102, Solyc07g061940.3', enzyme: 'dCas9-PmCDA1, dCas9-PmCDA2', archive: '', library: '', pmid: '30669298'},
            {organism: 'Homo sapiens', biosample: 'SW579 cell', assay: 'Knockin by NHEJ – single genomic target', genes: 'HDAC1, HDAC2', enzyme: 'Cas9', archive: '', library: '', pmid: '30669676'},
            {organism: 'Homo sapiens', biosample: 'HL-60', assay: 'Insertion by HDR/MMEJ', genes: 'CFTR', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30670178'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cdkn1b', enzyme: 'Cas9', archive: '', library: '', pmid: '30671114'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Plac8', enzyme: 'Cas9', archive: '', library: '', pmid: '30671116'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Gnao1', enzyme: 'SpCas9', archive: '', library: '', pmid: '30682176'},
            {organism: 'Mus musculus', biosample: 'myoblast, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'Ctnnb1', enzyme: 'Cas9', archive: '', library: '', pmid: '30683662'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, zygote', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'Bag3, Camk2a, Glrb, Slc39a6, Tbx6, Tyr', enzyme: 'HiFi Cas9', archive: '', library: '', pmid: '30684509'},
            {organism: 'Homo sapiens', biosample: 'A549', assay: 'Knockout by NHEJ – single genomic target', genes: 'B3GAT3, B4GALT7, SLC35B2', enzyme: 'Cas9', archive: '', library: '', pmid: '30684694'},
            {organism: 'Homo sapiens', biosample: 'Jurkat, K562, MOLM-13 cell, TF-1 cell', assay: 'Knockin by NHEJ – single genomic target', genes: 'RUNX1', enzyme: 'Cas9', archive: '', library: '', pmid: '30690039'},
            {organism: 'Homo sapiens', biosample: 'Caco-2', assay: 'Knockout by NHEJ – single genomic target', genes: 'ITGB1', enzyme: 'Cas9', archive: '', library: '', pmid: '30700983'},
            {organism: 'Oryza sativa Japonica Group', biosample: 'Oryza sativa cv. Nipponbare, plant embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'DEP1', enzyme: 'Cas9', archive: '', library: '', pmid: '30706248'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Dual sgRNA-directed deletion, Knockout by NHEJ – single genomic target', genes: 'Mir741, Mir871, Mir880', enzyme: 'Cas9', archive: '', library: '', pmid: '30707741'},
            {organism: 'Homo sapiens, Microtus ochrogaster', biosample: 'HEK293T, zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'OXTR, oxytocin receptor', enzyme: 'Cas9', archive: '', library: '', pmid: '30713102'},
            {organism: 'Mus musculus', biosample: 'NMRI Mouse, zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Fam83h', enzyme: 'Cas9n (D10A)', archive: '', library: '', pmid: '30714208'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'map11', enzyme: 'Cas9', archive: '', library: '', pmid: '30715179'},
            {organism: 'Mus musculus', biosample: 'GC-1 spg cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'Fto', enzyme: 'Cas9', archive: '', library: '', pmid: '30719031'},
            {organism: 'Rattus norvegicus', biosample: 'hippocampal neuron, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'Nfasc', enzyme: 'Cas9', archive: '', library: '', pmid: '30723396'},
            {organism: 'Homo sapiens', biosample: 'SK-MEL-30', assay: 'Knockout by NHEJ – single genomic target', genes: 'MLANA', enzyme: 'Cas9', archive: '', library: '', pmid: '30723467'},
            {organism: 'Homo sapiens', biosample: 'HepG2, HuH-7', assay: 'Knockout by NHEJ – single genomic target, Transcriptional inhibition', genes: 'BRD4, CDK7, EP300, MED1, PRPSAP1, SPHK1', enzyme: 'Cas9, dCas9-KRAB', archive: '', library: '', pmid: '30723918'},
            {organism: 'Homo sapiens', biosample: 'U937', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'SQLE', enzyme: 'Cas9', archive: 'Journal website', library: 'GeCKO v2', pmid: '30734978'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'GRIN3A', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30741440'},
            {organism: 'Mus musculus', biosample: 'obsolete_C57BL/6, zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Gch1', enzyme: 'Cas9', archive: '', library: '', pmid: '30742839'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'csf3r', enzyme: 'Cas9', archive: '', library: '', pmid: '30742890'},
            {organism: 'Mus musculus', biosample: 'C57BL/6NJ, zygote', assay: 'Knockin by NHEJ – single genomic target', genes: 'Fabp7', enzyme: 'hSpCas9 (D10A)', archive: '', library: '', pmid: '30765249'},
            {organism: 'Mus musculus', biosample: 'BV-2 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'Abcd1, Abcd2', enzyme: 'Cas9', archive: '', library: '', pmid: '30769094'},
            {organism: 'Macaca mulatta', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'PINK1', enzyme: 'SpCas9', archive: '', library: '', pmid: '30770867'},
            {organism: 'Mus musculus', biosample: 'ES-E14TG2a', assay: 'Knockout by NHEJ – single genomic target', genes: 'Emp2', enzyme: 'eSpCas9', archive: '', library: '', pmid: '30773261'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Dual sgRNA-directed deletion', genes: 'Il2ra', enzyme: 'Cas9', archive: 'NCBI Sequence Read Archive', library: '', pmid: '30793048'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Gata4', enzyme: 'hSpCas9', archive: '', library: '', pmid: '30793514'},
            {organism: 'Homo sapiens', biosample: 'HO-8910 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'MUC16', enzyme: 'Cas9', archive: '', library: '', pmid: '30795761'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Rnf146', enzyme: 'Cas9', archive: '', library: '', pmid: '30796047'},
            {organism: 'Homo sapiens', biosample: 'DLD1', assay: 'Knockout by NHEJ – single genomic target', genes: 'ITPR3', enzyme: 'Cas9', archive: '', library: '', pmid: '30796197'},
            {organism: 'Homo sapiens', biosample: 'H9', assay: 'Insertion by HDR/MMEJ', genes: 'TERF2IP', enzyme: 'Cas9', archive: '', library: '', pmid: '30796637'},
            {organism: 'Homo sapiens', biosample: 'H9', assay: 'Dual sgRNA-directed deletion', genes: 'MKRN3', enzyme: 'SpCas9', archive: '', library: '', pmid: '30800097'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'bhlhe22, nkx6.1, prdm12b', enzyme: 'Cas9', archive: '', library: '', pmid: '30813944'},
            {organism: 'Homo sapiens', biosample: 'HeLa', assay: 'Knockout by NHEJ – single genomic target', genes: 'VAMP7', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30815249'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Izumo1', enzyme: 'Cas9', archive: '', library: '', pmid: '30816314'},
            {organism: 'Homo sapiens', biosample: 'HCT116, HEK293', assay: 'Knockin by NHEJ – single genomic target', genes: 'STIM1, STIM2', enzyme: 'Cas9', archive: '', library: '', pmid: '30824535'},
            {organism: 'Oryctolagus cuniculus', biosample: 'New Zealand White Rabbit, zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'DMP1', enzyme: 'Cas9', archive: '', library: '', pmid: '30827034'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'Polr3h', enzyme: 'Cas9', archive: '', library: '', pmid: '30830215'},
            {organism: 'Homo sapiens', biosample: 'MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'SIAH2', enzyme: 'Cas9', archive: '', library: '', pmid: '30833558'},
            {organism: 'Mus musculus', biosample: 'C57BL/6J, embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Iqsec2', enzyme: 'Cas9', archive: '', library: '', pmid: '30842726'},
            {organism: 'Sus scrofa', biosample: 'mesenchymal stromal cell, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'ZBTB48', enzyme: 'Cas9', archive: '', library: '', pmid: '30845965'},
            {organism: 'Mus musculus', biosample: 'mIMCD-3', assay: 'Knockout by NHEJ – single genomic target', genes: 'Ppargc1a', enzyme: 'Cas9', archive: '', library: '', pmid: '30870143'},
            {organism: 'Homo sapiens', biosample: 'MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'PMEPA1', enzyme: 'pSpCas9', archive: '', library: '', pmid: '30873542'},
            {organism: 'Homo sapiens', biosample: 'hTERT-RPE1 cell', assay: 'Insertion by HDR/MMEJ', genes: 'HGS, TSG101, VPS4B', enzyme: 'Cas9', archive: '', library: '', pmid: '30894482'},
            {organism: 'Mus musculus', biosample: 'embryonic fibroblast, Neuro-2a cell, primary cell line', assay: 'Dual sgRNA-directed deletion, Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'Slc26a4', enzyme: 'SaCas9', archive: '', library: '', pmid: '30898719'},
            {organism: 'Homo sapiens', biosample: 'OVCAR3, OVCAR4', assay: 'Knockout by NHEJ – single genomic target', genes: 'DOT1L', enzyme: 'Cas9', archive: '', library: '', pmid: '30899413'},
            {organism: 'Homo sapiens', biosample: 'SUM149PT', assay: 'Knockout by NHEJ – single genomic target', genes: 'AHR', enzyme: 'Cas9', archive: '', library: '', pmid: '30899591'},
            {organism: 'Homo sapiens', biosample: 'OVCAR3', assay: 'Knockout by NHEJ – single genomic target', genes: 'NANOG', enzyme: 'Cas9', archive: '', library: '', pmid: '30904337'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Plod2', enzyme: 'Cas9', archive: '', library: '', pmid: '30905411'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'AFG3L2', enzyme: 'SpCas9', archive: '', library: '', pmid: '30910913'},
            {organism: 'Homo sapiens', biosample: 'primary cultured cell, trabecular meshwork', assay: 'Knockout by NHEJ – single genomic target', genes: 'CAV1', enzyme: 'Cas9', archive: '', library: '', pmid: '30916825'},
            {organism: 'Homo sapiens', biosample: 'RWPE1', assay: 'Knockout by NHEJ – single genomic target', genes: 'TET2', enzyme: 'Cas9-GFP', archive: '', library: '', pmid: '30917865'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Dual sgRNA-directed deletion, Knockout by NHEJ – single genomic target', genes: 'CLPSL2, Epp13, GLB1L2, Gm1110, PATE1, PATE2, RNASE13', enzyme: 'Cas9', archive: '', library: '', pmid: '30927342'},
            {organism: 'Danio rerio', biosample: 'embryo, Tubingen Zebrafish', assay: 'Knockout by NHEJ – single genomic target', genes: 'adamts9', enzyme: 'Cas9', archive: '', library: '', pmid: '30951722'},
            {organism: 'Vibrio natriegens', biosample: 'Whole Organism', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'BA894_04220, BA894_13380, GFP', enzyme: 'dCas9, SpCas9', archive: 'NCBI Sequence Read Archive', library: 'GeCKO v2', pmid: '30962569'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'vwf', enzyme: 'nCas9n', archive: '', library: '', pmid: '30968393'},
            {organism: 'Capra hircus', biosample: 'embryonic fibroblast', assay: 'Knockout by NHEJ – single genomic target', genes: 'MSTN', enzyme: 'Cas9', archive: '', library: '', pmid: '30981084'},
            {organism: 'Homo sapiens', biosample: 'A172', assay: 'Knockout by NHEJ – single genomic target', genes: 'IGF2BP1', enzyme: 'Cas9', archive: '', library: '', pmid: '31000197'},
            {organism: 'Homo sapiens', biosample: 'Peripheral Blood Mononuclear Cell, primary cell line, THP-1', assay: 'Knockout by NHEJ – single genomic target', genes: 'IGF2BP1', enzyme: 'Cas9', archive: '', library: '', pmid: '31000200'},
            {organism: 'Homo sapiens', biosample: 'CWR22-Rv1 cell', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'AR', enzyme: 'Cas9', archive: '', library: '', pmid: '31006810'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'magi2a, magi2b', enzyme: 'Cas9', archive: '', library: '', pmid: '31010479'},
            {organism: 'Homo sapiens', biosample: 'HepG2, MDAMB231, PC-3', assay: 'Knockout by NHEJ – single genomic target', genes: 'CDK5', enzyme: 'SpCas9', archive: '', library: '', pmid: '31013770'},
            {organism: 'Homo sapiens', biosample: 'HepG2', assay: 'Knockout by NHEJ – single genomic target', genes: 'TRAF3', enzyme: 'Cas9', archive: '', library: '', pmid: '31016787'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Spata13', enzyme: 'Cas9', archive: '', library: '', pmid: '31020388'},
            {organism: 'Mus musculus', biosample: 'MIN6', assay: 'Knockout by NHEJ – single genomic target', genes: 'Jund', enzyme: 'Cas9', archive: '', library: '', pmid: '31023625'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Dual sgRNA-directed deletion, Knockout by NHEJ – single genomic target', genes: 'Dmd', enzyme: 'Cas9', archive: '', library: '', pmid: '31028078'},
            {organism: 'Homo sapiens', biosample: 'THP-1', assay: 'Knockout by NHEJ – single genomic target', genes: 'EGR1', enzyme: 'Cas9', archive: '', library: '', pmid: '31028249'},
            {organism: 'Arabidopsis thaliana', biosample: 'Flower', assay: 'Knockout by NHEJ – single genomic target', genes: 'AT5G18400', enzyme: 'Cas9', archive: '', library: '', pmid: '31034471'},
            {organism: 'Rattus norvegicus', biosample: 'embryonic fibroblast, zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Tbc1d4', enzyme: 'Cas9', archive: '', library: '', pmid: '31034517'},
            {organism: 'Homo sapiens', biosample: 'MCF-7, MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'SHH', enzyme: 'Cas9', archive: '', library: '', pmid: '31036836'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'aub, bru1, CG5800, gw, mei-P26, piwi, tud, vas', enzyme: 'Cas9', archive: '', library: '', pmid: '31037730'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Lhfp', enzyme: 'Cas9', archive: '', library: '', pmid: '31042701'},
            {organism: 'Escherichia coli BW25113', biosample: 'Whole Organism', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'dnaG, fabG', enzyme: 'SpCas9', archive: '', library: '', pmid: '31047915'},
            {organism: 'Homo sapiens', biosample: 'MOLM-13 cell, MV4-11 cell, OCI-AML2', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'BAX, BCL2L11, EPHA7, FAU, KMT2C, MAD2L2, MAPK3, PDCD10, PMAIP1, PRSS21, PYCARD, TFDP1, TP53', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '31048320'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'glra1, glra2, glra3, glra4a, glra4b', enzyme: 'Cas9, Nanos-Cas9', archive: '', library: '', pmid: '31048868'},
            {organism: 'Homo sapiens', biosample: 'SH-SY5Y', assay: 'Knockout by NHEJ – single genomic target', genes: 'E2F7', enzyme: 'Cas9', archive: '', library: '', pmid: '31053300'},
            {organism: 'Homo sapiens, Sus scrofa', biosample: 'HEK293T, RCB0534 cell', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'ENSSSCG00000035293, IGF2', enzyme: 'SpCas9, Streptococcus thermophilus Cas9', archive: '', library: '', pmid: '31057603'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Nod2', enzyme: 'Cas9', archive: '', library: '', pmid: '31065630'},
            {organism: 'Mus musculus', biosample: 'Embryonic Stem Cell', assay: 'Insertion by HDR/MMEJ', genes: 'Bcl11b', enzyme: 'Cas9', archive: '', library: '', pmid: '31067316'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'a, Axin1', enzyme: 'Cas9', archive: '', library: '', pmid: '31073336'},
            {organism: 'Homo sapiens', biosample: 'KATOIII', assay: 'Knockout by NHEJ – treated sample', genes: '', enzyme: 'Cas9', archive: '', library: 'GeCKO v2', pmid: '31076567'},
            {organism: 'Mus musculus', biosample: 'Embryonic Stem Cell', assay: 'Knockin by NHEJ – single genomic target, Knockout by NHEJ – proliferation, Knockout by NHEJ – treated sample', genes: 'Actbl2, Apc, Arnt, Arrdc3, Atp2b1, Axin1, Bnip3, Csde1, Ddx17, Ddx5, Fbxw7, Fgfr1, Fig4, Flcn, Frs2, Gapdhs, Lamtor2, Lamtor4, Nf2, Olfr478, Otx2, Ptpn11, Ptpn2, Rab7, Ranbp3, Rragc, Spns1, Spop, Tcf7l1, Tfe3, Trp53, Tsc1, Tsc2, Vps11, Vps16, Vps18, Vps29, Vps35, Vps39, Vps54, Zfp281', enzyme: 'Cas9', archive: 'NCBI Sequence Read Archive', library: 'GeCKO v2', pmid: '31104942'},
            {organism: 'Homo sapiens', biosample: 'MDAMB231', assay: 'Knockout by NHEJ – single genomic target', genes: 'RELA', enzyme: 'Cas9', archive: '', library: '', pmid: '31105691'},
            {organism: 'Sus scrofa', biosample: 'fetal cell line, fibroblast, primary cell line', assay: 'Knockout by NHEJ – single genomic target', genes: 'B2M', enzyme: 'hSpCas9', archive: '', library: '', pmid: '31119817'},
            {organism: 'Drosophila melanogaster', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Zasp66, Zasp67', enzyme: 'Cas9', archive: '', library: '', pmid: '31123042'},
            {organism: 'Fusarium verticillioides 7600', biosample: 'Whole Organism', assay: 'Knockout by NHEJ – single genomic target', genes: 'GP63-1', enzyme: 'Cas9', archive: '', library: '', pmid: '31123471'},
            {organism: 'Homo sapiens', biosample: 'CD14-positive monocyte, HEK293, HeLa, primary cell line, THP-1, U937', assay: 'Knockout by NHEJ – single genomic target', genes: 'CGAS, SLC19A1', enzyme: 'Cas9', archive: 'Journal website', library: 'GeCKO v2', pmid: '31126740'},
            {organism: 'Homo sapiens', biosample: 'Caco-2', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'CFTR', enzyme: 'Cas9', archive: '', library: '', pmid: '31126900'},
            {organism: 'Homo sapiens', biosample: 'HCT116, RKO', assay: 'Insertion by HDR/MMEJ', genes: 'TK1', enzyme: 'hSpCas9', archive: '', library: '', pmid: '31138881'},
            {organism: 'Homo sapiens', biosample: 'Jurkat', assay: 'Knockout by NHEJ – single genomic target', genes: 'DDX58', enzyme: 'SpCas9', archive: '', library: '', pmid: '31142372'},
            {organism: 'Oryzias latipes', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'ENSORLG00000005573, yap1', enzyme: 'Cas9', archive: '', library: '', pmid: '31142542'},
            {organism: 'Homo sapiens', biosample: 'A375', assay: 'Knockout by NHEJ – single genomic target', genes: 'RUNX2', enzyme: 'Cas9', archive: '', library: '', pmid: '31142788'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Slc26a4', enzyme: 'Cas9', archive: '', library: '', pmid: '31155292'},
            {organism: 'Vitis vinifera', biosample: 'callus, cell suspension culture', assay: 'Knockout by NHEJ – single genomic target', genes: 'VIT_09s0002g00100', enzyme: 'Plant optimised SpCas9', archive: '', library: '', pmid: '31156675'},
            {organism: 'Homo sapiens', biosample: 'SAOS-2 cell', assay: 'Insertion by HDR/MMEJ', genes: 'HBP1', enzyme: 'SpCas9', archive: '', library: '', pmid: '31164647'},
            {organism: 'Coturnix japonica', biosample: 'blastoderm', assay: 'Knockout by NHEJ – single genomic target', genes: 'MLPH', enzyme: 'Cas9', archive: '', library: '', pmid: '31209054'},
            {organism: 'Oryza sativa Japonica Group', biosample: 'callus', assay: 'Knockout by NHEJ – single genomic target', genes: 'OsCKX9', enzyme: 'Cas9', archive: '', library: '', pmid: '31235564'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'tp63', enzyme: 'Cas9', archive: '', library: '', pmid: '31296872'},
            {organism: 'Arabidopsis thaliana', biosample: 'Flower', assay: 'Knockout by NHEJ – single genomic target', genes: 'KASI', enzyme: 'Cas9', archive: '', library: '', pmid: '31297160'},
            {organism: 'Candida orthopsilosis Co 90-125', biosample: 'SK-MEL-28', assay: 'Knockout by NHEJ – single genomic target', genes: 'CORT_0G04310', enzyme: 'Cas9', archive: '', library: '', pmid: '31352406'},
            {organism: 'Hordeum vulgare subsp. vulgare', biosample: 'plant embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'HORVU1Hr1G042360, HORVU3Hr1G019850', enzyme: 'Cas9', archive: '', library: '', pmid: '31357516'},
            {organism: 'Physcomitrella patens', biosample: 'immortal mucosa of vagina-derived cell line cell, Plant Tissue, Cells', assay: 'Knockout by NHEJ – single genomic target', genes: 'Pp3c14_11190, Pp3c17_8330, Pp3c1_35410', enzyme: 'Cas9', archive: '', library: '', pmid: '31432295'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'Cnr1', enzyme: 'Cas9-NLS', archive: '', library: '', pmid: '31445429'},
            {organism: 'Callithrix jacchus', biosample: 'embryo, fibroblast', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'KIT, SHANK3', enzyme: 'hCas9', archive: '', library: '', pmid: '31481684'},
            {organism: 'Homo sapiens', biosample: 'A2780', assay: 'Knockout by NHEJ – treated sample', genes: '', enzyme: 'Cas9', archive: 'ArrayExpress', library: 'GeCKO v2', pmid: '31508509'},
            {organism: 'Felis catus', biosample: 'AK-D cell, Fcwf-4 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'IFNAR2', enzyme: 'Cas9', archive: '', library: '', pmid: '31539770'},
            {organism: 'Glycine max', biosample: 'plant embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'GLYMA_06G145800', enzyme: 'hSpCas9', archive: '', library: '', pmid: '31611562'},
            {organism: 'Drosophila melanogaster', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'per', enzyme: 'Cas9', archive: '', library: '', pmid: '31613223'},
            {organism: 'Homo sapiens', biosample: 'MHCC97-L cell', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'PHGDH', enzyme: 'Cas9', archive: 'NCBI BioProject', library: 'GeCKO v2', pmid: '31615983'},
            {organism: 'Oryctolagus cuniculus', biosample: 'zygote', assay: 'Dual sgRNA-directed deletion', genes: 'mc1R', enzyme: 'hSpCas9', archive: '', library: '', pmid: '31620174'},
            {organism: 'Homo sapiens', biosample: 'induced pluripotent stem cell', assay: 'Insertion by HDR/MMEJ', genes: 'HBB', enzyme: 'SpCas9', archive: '', library: '', pmid: '31631510'},
            {organism: 'Caenorhabditis elegans', biosample: 'Gonad', assay: 'Insertion by HDR/MMEJ, Knockout by NHEJ – single genomic target', genes: 'dpy-10, rsp-4, sftb-1, uaf-2', enzyme: 'Cas9', archive: '', library: '', pmid: '31634348'},
            {organism: 'Homo sapiens', biosample: 'ES-2 cell, OVCAR3', assay: 'Knockout by NHEJ – single genomic target', genes: 'LPAR2, LPAR3, LPAR6', enzyme: 'SpCas9', archive: '', library: '', pmid: '31636669'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'pcyt2', enzyme: 'Cas9', archive: '', library: '', pmid: '31637422'},
            {organism: 'Homo sapiens', biosample: 'HuCCT-1 cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'CSNK2A1', enzyme: 'Cas9', archive: '', library: '', pmid: '31641101'},
            {organism: 'Solanum lycopersicum', biosample: 'cotyledon', assay: 'Knockout by NHEJ – single genomic target', genes: 'Solyc01g097440.3', enzyme: 'Cas9', archive: '', library: '', pmid: '31645950'},
            {organism: 'Homo sapiens', biosample: 'HCT116, KATOIII, NUGC-3 cell, RCB2278 cell, SNU-1 cell, SNU-638', assay: 'Knockout by NHEJ – proliferation, Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'NIPBL', enzyme: 'Cas9', archive: '', library: 'GeCKO v2', pmid: '31648989'},
            {organism: 'Arabidopsis thaliana', biosample: 'Flower', assay: 'Dual sgRNA-directed deletion', genes: 'AP1, SVP, TFL1', enzyme: 'Cas9', archive: '', library: '', pmid: '31666960'},
            {organism: 'Oryza sativa Japonica Group', biosample: 'callus', assay: 'Knockout by NHEJ – single genomic target', genes: 'OsHXK5', enzyme: 'Cas9', archive: '', library: '', pmid: '31671177'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'ghrl', enzyme: 'Cas9', archive: '', library: '', pmid: '31673996'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Insertion by HDR/MMEJ', genes: 'Gt(ROSA)26Sor', enzyme: 'Cas9', archive: '', library: '', pmid: '31676125'},
            {organism: 'Homo sapiens', biosample: 'HeLa, myoblast, primary cell line', assay: 'Dual sgRNA-directed deletion', genes: 'B2M, SMCHD1', enzyme: 'SpCas9', archive: '', library: '', pmid: '31676591'},
            {organism: 'Homo sapiens', biosample: 'induced pluripotent stem cell', assay: 'Knockout by NHEJ – single genomic target', genes: 'WWTR1', enzyme: 'Cas9', archive: '', library: '', pmid: '31677525'},
            {organism: 'Homo sapiens', biosample: 'HEK293', assay: 'Knockout by NHEJ – single genomic target', genes: 'XYLT2', enzyme: 'Cas9', archive: '', library: '', pmid: '31677793'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'anln, kmt2d, smchd1', enzyme: 'Cas9', archive: '', library: '', pmid: '31681410'},
            {organism: 'Homo sapiens', biosample: 'induced pluripotent stem cell', assay: 'Insertion by HDR/MMEJ', genes: 'PDX1', enzyme: 'Cas9', archive: '', library: '', pmid: '31683099'},
            {organism: 'Culex quinquefasciatus', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'CPIJ005542', enzyme: 'SpCas9', archive: '', library: '', pmid: '31693260'},
            {organism: 'Mus musculus', biosample: 'bone marrow-derived macrophage', assay: 'Knockout by NHEJ – single genomic target', genes: 'Dgat1', enzyme: 'Cas9', archive: '', library: '', pmid: '31694081'},
            {organism: 'Homo sapiens', biosample: 'HEK293T, MKN45', assay: 'Knockout by NHEJ – single genomic target', genes: 'CEACAM5', enzyme: 'Cas9', archive: '', library: '', pmid: '31695778'},
            {organism: 'Homo sapiens', biosample: 'HEK293T', assay: 'Knockout by NHEJ – single genomic target', genes: 'PLAC8', enzyme: 'SpCas9', archive: '', library: '', pmid: '31696435'},
            {organism: 'Oryctolagus cuniculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'ENSOCUG00000001018', enzyme: 'Cas9', archive: '', library: '', pmid: '31720743'},
            {organism: 'Homo sapiens', biosample: 'Umbilical Cord Blood-Derived Mesenchymal Stem Cells', assay: 'Knockout by NHEJ – single genomic target', genes: 'B2M', enzyme: 'Cas9', archive: '', library: '', pmid: '31729180'},
            {organism: 'Homo sapiens', biosample: 'H1-hESC', assay: 'Insertion by HDR/MMEJ', genes: 'ERF', enzyme: 'Cas9', archive: '', library: '', pmid: '31743839'},
            {organism: 'Mus musculus', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'Rbm14', enzyme: 'Cas9', archive: '', library: '', pmid: '31794640'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'tnnt2a', enzyme: 'Zebrafish optimized Cas9', archive: '', library: '', pmid: '31796423'},
            {organism: 'Macaca mulatta', biosample: 'zygote', assay: 'Knockout by NHEJ – single genomic target', genes: 'MCPH1', enzyme: 'Cas9', archive: '', library: '', pmid: '31797925'},
            {organism: 'Bombyx mori', biosample: 'ovum', assay: 'Knockout by NHEJ – single genomic target', genes: 'IGFLP', enzyme: 'Cas9', archive: '', library: '', pmid: '31804598'},
            {organism: 'Homo sapiens', biosample: 'SW1990', assay: 'Knockout by NHEJ – single genomic target', genes: 'YAP1', enzyme: 'Cas9', archive: '', library: '', pmid: '31810603'},
            {organism: 'Homo sapiens', biosample: 'HL-60, KG1', assay: 'Knockout by NHEJ – single genomic target', genes: 'BIRC5', enzyme: 'Cas9', archive: '', library: '', pmid: '31819702'},
            {organism: 'Mus musculus', biosample: 'embryo', assay: 'Insertion by HDR/MMEJ', genes: 'Ins1', enzyme: 'Cas9', archive: '', library: '', pmid: '31821343'},
            {organism: 'Glycine max', biosample: 'seedling', assay: 'Knockout by NHEJ – single genomic target', genes: 'GLYMA_06G207800', enzyme: 'Dicotyledon optimised Cas9-NLS-NLS', archive: '', library: '', pmid: '31824524'},
            {organism: 'Homo sapiens', biosample: 'MCF-7', assay: 'Knockout by NHEJ – proliferation, Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'ARID1A', enzyme: 'Cas9, SpCas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '31913353'},
            {organism: 'Homo sapiens', biosample: 'AMO-1, RPMI8226, U266', assay: 'Insertion by HDR/MMEJ', genes: 'APOBEC3B', enzyme: 'SpCas9', archive: '', library: '', pmid: '31914134'},
            {organism: 'Danio rerio', biosample: 'embryo', assay: 'Knockout by NHEJ – single genomic target', genes: 'smyhc1', enzyme: 'Cas9', archive: '', library: '', pmid: '31914689'},
            {organism: 'Homo sapiens', biosample: 'K562', assay: 'Knockout by NHEJ – single genomic target, Knockout by NHEJ – treated sample', genes: 'B2M, HLA-E, IFNGR2', enzyme: 'Cas9', archive: 'Gene Expression Omnibus', library: 'GeCKO v2', pmid: '31921143'},            
          ]}
          title="Publications"
        />
      </div>
    )
  }
}

ReactDOM.render(<App />, document.querySelector('#app'));

// ReactDOM.render(<App />, document.getElementById('react-div'));